ALTER TABLE users
  ALTER COLUMN first_name DROP NOT NULL,
  ALTER COLUMN username   DROP NOT NULL,
  ALTER COLUMN last_name  DROP NOT NULL,
  ALTER COLUMN role       DROP NOT NULL;

ALTER TABLE users
  ALTER COLUMN username   DROP DEFAULT,
  ALTER COLUMN first_name DROP DEFAULT,
  ALTER COLUMN last_name  DROP DEFAULT,
  ALTER COLUMN role       DROP DEFAULT;


ALTER TABLE users
  DROP CONSTRAINT IF EXISTS users_username_key;